apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
  mongo-local-port: "27017"
  mongo-database: todo-app
  app-env: local
  log-level: debug
  jwt-secret-key: this-is-our-secret-key
