apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi-deployment
  labels:
    app: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - name: todoapi
          image: nihalwashere/todo-api:1.1
          ports:
            - containerPort: 7000
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGODB_LOCAL_PORT
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-local-port
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-database
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: app-env
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: log-level
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: jwt-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi-service
spec:
  type: NodePort
  selector:
    app: todoapi
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30100
